### ISSUE TITLE
Unable to use my assets

### ISSUE THREAD

**Issue by MirrorAzure** [SpaceManiac/HamSandwich#12]
I tried to add my tileset to the game so I created a "tilegfx" folder with bmp-image in it:
![File in directory](https://user-images.githubusercontent.com/54669636/201519932-f1220c12-8bc5-4107-86a9-273f47106b25.png)
When I launch the game, there is my tileset in the editor list:
![Tiles in menu](https://user-images.githubusercontent.com/54669636/201519944-6061b300-914b-4b51-bae1-9c37d72fdcde.png)
But when I try to load it, there is an error: ```ERROR: open_sdl(tilegfx/TestTiles.bmp): not found in any vfs```

Here is console log:
```
[0/2] Re-checking globbed directories...
ninja: no work to do.
==== Running supreme (windows-x86_64-debug) ====
DEBUG: auto 0 required: @nsis@installers/supreme8_install.exe
DEBUG: auto 1 disabled: @zip@installers/all_supreme_worlds.zip
DEBUG: auto 2 disabled: @zip@installers/sup_GloomValleyRemastered.zip
DEBUG: auto assets: assets/supreme
DEBUG: auto appdata: appdata/supreme
INFO: audio format: freq=44100, channels=2, format=0x8010
INFO: window format: SDL_PIXELFORMAT_RGB888
INFO: renderer: direct3d
INFO:   flags: accelerated vsync ttex
INFO:   texture: (16384, 16384)
INFO:   formats (3):
INFO:     SDL_PIXELFORMAT_ARGB8888
INFO:     SDL_PIXELFORMAT_YV12
INFO:     SDL_PIXELFORMAT_IYUV
ERROR: open_stdio(hiscore.dat): not found in any vfs
ERROR: open_stdio(hitime.dat): not found in any vfs
ERROR: open_sdl(tilegfx/TestTiles.bmp): not found in any vfs
```
Same goes with custom sounds and graphics.

I learned about your project back in January 2022. I tried to modify the game in the old version, and everything worked for me. Now I decided to install a new one and ran into the above problem.

Thanks in advance for your reply.

**Comment by SpaceManiac** [comment]
Looks like the issue may have been introduced in March. Weird that it didn't get noticed earlier. I pushed a change that should fix it.

If you run into issues with the music, try using the "MSYS2 MinGW x86" console instead of "MSYS2 MinGW x64".

**Comment by MirrorAzure** [comment]
Thank you!
It solved the problem.
