### ISSUE TITLE
Option to include contents of all_supreme_worlds.zip (DLW files and replacement DAT file) for Supreme with Cheese

### ISSUE THREAD

**Issue by BiggerJ** [SpaceManiac/HamSandwich#8]
The zip can be downloaded at <https://hamumu.itch.io/dr-lunatic-supreme-with-cheese>. Such an option would, of course, require the user to download the zip themselves, as with the original game's installer.

Edit: I just remembered that Loonyland 2 has multiple optional add-ons available on its itch.io page.

**Comment by SpaceManiac** [comment]
HamSandwich now includes a launcher where you can choose whether to download optional add-ons such as the "All Supreme Worlds" collection or the Loonyland 2 addons.
